services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin_postgres
      POSTGRES_PASSWORD: 1231m0d__xaw,oxp
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
